server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: demo
    profile: dev
    version: 1.0.0
    description: Demo application for Spring Boot
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/ecom_gnurt
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:123@abc}
  driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-dll: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
  cloud:
    config:
      uri: http://localhost:8888
      fail-fast: true
      retry:
        max-attempts: 3
        initial-interval: 1000
        max-interval: 5000
        multiplier: 2.0
application:
  token:
    key: ${TOKEN_KEY:trungnt@1999}
    expiration_access_token: 900
    expiration_refresh_token: 86400

  